apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: development
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  sourceRepos:
    - "*"
  destinations:
    - server: https://kubernetes.default.svc
      namespace: dev
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app
spec:
  project: development
  source:
    repoURL: https://github.com/5EGFAULT/iot-p3.git
    path: "."
    directory:
      include: "app.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
