apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-dpl
spec:
  selector:
    matchLabels:
      app: app-dpl
  template:
    metadata:
      labels:
        app: app-dpl
    spec:
      containers:
        - name: app-container
          image: wil42/playground:v1
          # image: hashicorp/http-echo
          # args: ["-text=Hello from app1212", "-listen=:8888"]
          ports:
            - containerPort: 8888

---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: app-dpl
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
      nodePort: 30088
  type: NodePort
